apiVersion: apps/v1
kind: Deployment
metadata:
  name: example4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example4
  template:
    metadata:
      labels:
        app: example4
    spec:
      containers:
      - name: example4
        image: erbolat97/example4:latest
        ports:
        - containerPort: 8056
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:Zxcvbnm123@host:5432/example4"

---
apiVersion: v1
kind: Service
metadata:
  name: example4-service
spec:
  type: NodePort
  selector:
    app: example4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8056
      nodePort: 30001  # Можно указать порт от 30000 до 32767